### PR TITLE
No details file

### LINKED ISSUE #282: How to check for available youtube-dl binrary updates before running the update
Hi,

i am using youtube-dl within my electron project and discovered the updater function. I am using the example code from the project readme to update the binary

```
const downloader = require('youtube-dl/lib/downloader')

downloader('path/to-binary', function error(err, done) {
  'use strict'
  if (err) throw err

  console.log(done)
})
```

Question:
Is there a way to detect if there is an update available before running the actual update process?
I would avoid updating to the already existing version (wasting process time and bandwidth)

### PR DESCRIPTION
**Pull request by brunobg**
The details file is used to store the youtube-dl version (which can be stale and should be retrived from the binary) and the binary path (with a default) that can be altered externally. This conflicts with packagers, because this file is read before a different path can be set and has to be included as an asset.

This patch removes the details file altogether. The same default path for youtube-dl is maintained, and if a different path is supplied it's only checked at runtime. So it's safe to include in packagers and there's no breaking changes.

Changing this will help to fix #282 later.

### CODE REVIEW

**Comment by brunobg** [comment]
Ahn, sorry for the merges but they seem harmless and nops. If necessary I can create another PR without them.

**Comment by Tzahi12345** [comment]
Would this actually fix #282? I have a workaround where I get the current version from the details file and check the youtube-dl `tags` page to see if there's an update, this PR would (I think) make this method impossible:

```
let current_youtubedl_details = JSON.parse(fs.readFileSync(current_youtubedl_details_path));
let current_version = current_youtubedl_details['version'];

// got current version, now let's check if there's a newer one available
let youtubedl_api_path = 'https://api.github.com/repos/ytdl-org/youtube-dl/tags';
fetch(youtubedl_api_path, {method: 'Get'})
.then(async res => res.json())
.then(async (json) => {
	// check if the versions are different
	if (!json || !json[0]) {
		resolve(false);
		return false;
	}
	const latest_update_version = json[0]['name'];
	if (current_version !== latest_update_version) {
		// new version available, update!
		downloader(binary_path, function error(err, done) {
			if (err) {
				console.error(err);
				resolve(false);
			}
			console.log(`Binary successfully updated: ${current_version} -> ${latest_update_version}`);
			resolve(true);
		});
	}
});
```

**Comment by brunobg** [comment]
The details file stores information that is available from the binary itself. I think it's redundant and may possibly be out of synchrony. This PR would break your code, but you could get the info by running youtube-dl with --version instead of reading the details file. I don't know if this PR will be approved, however.

I ended up needing so many changes from this package that I wrote a separate module, which already checks the version to avoid re-downloads, at https://github.com/Corollarium/node-youtube-dl.

**Review by AwasthiDevanshu — APPROVED** [review]

**Comment by Kikobeats** [comment]
Hey @brunobg sorry for the delay and thanks for this.

I updated your contribution in a new PR. See #352

hopefully, it will land soon 😃

**Pull request closed without merging**
