### PR TITLE
always add range header on data request

### PR DESCRIPTION
**Pull request by fredericgermain**
Hi !

I notice the download was very slow for audio, so I compared with python youtube-dl.
I find out that the youtube server is really slow if the Range: header is missing.
This commit always adds a Range: header

Fixes https://github.com/przemyslawpluta/node-youtube-dl/issues/251

### CODE REVIEW

**Comment by Kikobeats** [comment]
Awesome, thanks for that!

is this a thing that is related with an specific provider (e.g., YouTube) or potentially could speed up any download?

**Comment by fredericgermain** [comment]
It's really related to youtube, and maybe only audio downloads? I was only interested in audio and didn't check on video that much, but I don't see any problem on the tests.

This header makes a huge difference on how fast the youtube server send data. But I have no idea why, it shouldn't be necessary from HTTP spec.
It looks like the server makes pauses every ~130672 bytes when no range, so I added 3:20 music video for test. Without the range hack, `npm run test` takes around 2mins. Sometimes more the 3mins and then the transfer timeout and the test fails. With range header, it's around 40s (the audio download is < 1s).

I also made a commit to fix test on node 12 (and 10). It seems there are still some failures with node 8...

**Comment by Kikobeats** [comment]
Thanks for the explanation! I want to drop node8 in the next version, stay stunned!

**Comment by mayeaux** [comment]
Nice work @fredericgermain !

**Comment by fredericgermain** [comment]
Thanks for the new already available version 3.0.0 ! :)

**Pull request merged**
