### PR TITLE
docs: Add undocumented getYtdlBinary & setYtdlBinary functions

### LINKED ISSUE #258: Undocumented functions (setYtdlBinary & getYtdlBinary)
Hey,

I noticed there is are functions to get & set the binary path. These functions are not documented in the README.

It would be nice if they were. I am willing to make a PR with the additions if you do not mind.

### PR DESCRIPTION
**Pull request by AssetKid**
Closes #258

### CODE REVIEW

**Comment by AssetKid** [comment]
While editing the README, I did notice inconsistencies in the require statements.

``` js
var ytdl = require('youtube-dl');
```

``` js
var youtubedl = require('youtube-dl');
```

``` js
var youtubedl = require('./');
```

I can submit another PR (or edit this one) that normalizes the require statements for all examples and maybe use `const` and `let` instead of `var` where applicable.

Let me know.

**Comment by Kikobeats** [comment]
Thanks for that! I think edit on this PR is okay.

```
const youtubedl = require('youtube-dl')
``

^ we can use this way, also we can remove `;` since they are not present on the code 🙂

**Comment by AssetKid** [comment]
@Kikobeats Done!

**Comment by Kikobeats** [comment]
You rocks 😍

**Pull request merged**
