### PR TITLE
Send header because gets 403 if cookie is needed

### PR DESCRIPTION
**Pull request by kr4ssi**

### CODE REVIEW

**Comment by Kikobeats** [comment]
hello @kr4ssi, because I don't use cookie under youtube-dl, I need more context in order to land this into the source code 🙂.

A test verify this could be useful!

**Comment by kr4ssi** [comment]
Some hosters check the referer, others set a cookie on the video-page, therefore you can't get the stream if the headers are different.

**Comment by kr4ssi** [comment]
First of all, it was about the referer, not the cookie, sorry about that.
Also the site I had issues with (streamload.eu) doesn't seem to check it anymore.
Even though I sill think it would make sense to use the same http-header (at least user-agent, referer and cookies) as youtube-dl does (and provides in the info-output) to get the file, since youtube-dl uses specific http-headers for some hosters.

**Comment by Kikobeats** [comment]
Agree 🙂

**Comment by kr4ssi** [comment]
I'm not sure how this behaves if a proxy is used though.

**Comment by Kikobeats** [comment]
Let move this forward; Always we can undo this commit 🙂

**Pull request merged**
